# Generated by Django 2.2.7 on 2021-03-09 08:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='分类ID')),
                ('img', models.ImageField(upload_to='classify', verbose_name='分类图片')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('desc', models.CharField(blank=True, max_length=64, null=True, verbose_name='描述')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mall.Classify')),
            ],
            options={
                'db_table': 'mall_classify',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoredimensions', models.IntegerField(choices=[(11, '物流服务'), (12, '服务态度')], default=0, verbose_name='评论纬度')),
                ('is_nick', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_top', models.BooleanField(default=True, verbose_name='是否置顶')),
                ('comment_content', models.CharField(max_length=256, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否删除')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='标签ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='tags', verbose_name='主图')),
                ('code', models.CharField(blank=True, max_length=32, null=True, verbose_name='编码')),
                ('name', models.CharField(max_length=12, verbose_name='名称')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'mall_tag',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, verbose_name='商品ID')),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('desc', models.CharField(blank=True, max_length=256, null=True, verbose_name='简单描述')),
                ('content', models.TextField(verbose_name='商品描述')),
                ('types', models.SmallIntegerField(choices=[(11, '首页')], default=11, verbose_name='商品类型')),
                ('price', models.IntegerField(verbose_name='兑换价格(积分兑换)')),
                ('origin_paice', models.FloatField(verbose_name='原价')),
                ('img', models.ImageField(upload_to='product', verbose_name='主图')),
                ('buy_link', models.CharField(blank=True, max_length=256, null=True, verbose_name='购买链接')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('status', models.SmallIntegerField(choices=[(11, '销售中'), (12, '已售完'), (12, '已下架')], default=12, verbose_name='商品状态')),
                ('sku_count', models.IntegerField(default=0, verbose_name='库存')),
                ('remain_count', models.IntegerField(default=0, verbose_name='剩余库存')),
                ('view_count', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('score', models.FloatField(default=10, verbose_name='商品评分')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('classes', models.ManyToManyField(related_name='classes', to='mall.Classify', verbose_name='分类')),
                ('tag', models.ManyToManyField(related_name='tags', to='mall.Tag', verbose_name='标签')),
            ],
            options={
                'db_table': 'mall_product',
                'ordering': ['-reorder'],
            },
        ),
    ]
