# Generated by Django 2.2.7 on 2021-03-09 08:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='mall.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='商品ID'),
        ),
        migrations.AlterModelTable(
            name='comments',
            table='mall_comments',
        ),
    ]
