# Generated by Django 2.2.7 on 2021-03-09 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20210309_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mall.Product'),
        ),
    ]
