# Generated by Django 2.2.7 on 2021-03-09 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_remove_comments_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
