# Generated by Django 2.2.7 on 2021-03-09 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0006_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoredimensions', models.IntegerField(choices=[(11, '物流服务'), (12, '服务态度')], default=0, verbose_name='评论纬度')),
                ('is_nick', models.BooleanField(default=False, verbose_name='是否匿名')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_top', models.BooleanField(default=True, verbose_name='是否置顶')),
                ('comment_content', models.CharField(max_length=256, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否删除')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.Product')),
            ],
            options={
                'db_table': 'mall_comments',
            },
        ),
    ]
