# Generated by Django 2.2.7 on 2021-03-09 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
