# Generated by Django 2.2.7 on 2021-03-09 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mall', '0010_delete_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_nick', models.BooleanField(default=True, verbose_name='是否匿名')),
                ('reorder', models.SmallIntegerField(default=0, verbose_name='排序')),
                ('is_top', models.BooleanField(default=True, verbose_name='是否置顶')),
                ('comment_content', models.CharField(max_length=256, verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否删除')),
                ('score', models.FloatField(default=10.0, verbose_name='商品评分')),
                ('score_deliver', models.FloatField(default=10.0, verbose_name='配送服务评分')),
                ('score_package', models.FloatField(default=10.0, verbose_name='快递包装评分')),
                ('score_speed', models.FloatField(default=10.0, verbose_name='配送速度评分')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mall.Product', verbose_name='商品')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'mall_comments',
            },
        ),
    ]
