# Generated by Django 2.2.7 on 2021-03-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
