# Generated by Django 2.2.7 on 2021-03-26 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_phone_no_valid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='user',
            name='is_phone_no_valid',
            field=models.BooleanField(default=False, verbose_name='手机是否验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号码'),
        ),
    ]
