# -*- coding: utf-8 -*-
# @Time : 2021/3/7 0007
# @Author : yang
# @Email : 2635681517@qq.com
# @File : constants.py

"""系统模块的轮播图"""
SLIDER_TYPES_INDEX = 11
SLIDER_TYPES_CHOICES = (
    (SLIDER_TYPES_INDEX, '首页'),
)
"""系统模块-新闻通知"""
NEWS_TYPE_NEW = 11
NEWS_TYPE_NOTICE = 12
NEWS_TYPES_CHOICE = (
    (NEWS_TYPE_NEW, '新闻'),
    (NEWS_TYPE_NOTICE, '通知'),
)
# 商品的类型
PRODUCT_TYPE_ACTUALL=11
PRODUCT_TYPE_VIRTUAL=12
PRODUCT_TYPE_CHOICES=(
    (PRODUCT_TYPE_ACTUALL,'实物商品'),
    (PRODUCT_TYPE_VIRTUAL,'虚拟商品')
)
"""商品状态"""
PRODUCT_STATUS_SELL=11
PRODUCT_STATUS_LOST=12
PRODUCT_STATUS_OFF=12
PRODUCT_STATUS_CHOICES=(
    (PRODUCT_STATUS_SELL,'销售中'),
    (PRODUCT_STATUS_LOST,'已售完'),
    (PRODUCT_STATUS_OFF,'已下架')
)




