# -*- coding: utf-8 -*-
# @Time : 2021/3/7 0007
# @Author : yang
# @Email : 2635681517@qq.com
# @File : constants.py
# 登录后存储在session中的用户ID
LOGIN_SESSION_ID = 'user_id'
"""系统模块的轮播图"""
SLIDER_TYPES_INDEX = 11
SLIDER_TYPES_CHOICES = (
    (SLIDER_TYPES_INDEX, '首页'),
)
"""系统模块-新闻通知"""
NEWS_TYPE_NEW = 11
NEWS_TYPE_NOTICE = 12
NEWS_TYPES_CHOICE = (
    (NEWS_TYPE_NEW, '新闻'),
    (NEWS_TYPE_NOTICE, '通知'),
)
# 商品的类型
PRODUCT_TYPE_ACTUALL = 11
PRODUCT_TYPE_VIRTUAL = 12
PRODUCT_TYPE_CHOICES = (
    (PRODUCT_TYPE_ACTUALL, '实物商品'),
    (PRODUCT_TYPE_VIRTUAL, '虚拟商品')
)
"""商品状态"""
PRODUCT_STATUS_SELL = 11
PRODUCT_STATUS_LOST = 12
PRODUCT_STATUS_OFF = 12
PRODUCT_STATUS_CHOICES = (
    (PRODUCT_STATUS_SELL, '销售中'),
    (PRODUCT_STATUS_LOST, '已售完'),
    (PRODUCT_STATUS_OFF, '已下架')
)
"""评分纬度"""
COMMENTS_SCORE_LOGISTICSSERVICE = 11
COMMENTS_SCORE_SERVICEATTITUDE = 12
COMMENTS_SCORE_CHOICES = (
    (COMMENTS_SCORE_LOGISTICSSERVICE,'物流服务'),
    (COMMENTS_SCORE_SERVICEATTITUDE,'服务态度')
)

# 订单状态
ORDER_STATUS_INIT = 10
ORDER_STATUS_SUBMIT = 11
ORDER_STATUS_PAIED = 12
ORDER_STATUS_SENT = 13
ORDER_STATUS_DONE = 14
ORDER_STATUS_DELETED = 15
ORDER_STATUS_CHOICES = (
    (ORDER_STATUS_INIT, '购物车'),
    (ORDER_STATUS_SUBMIT, '已提交'),
    (ORDER_STATUS_PAIED, '已支付'),
    (ORDER_STATUS_SENT, '已发货'),
    (ORDER_STATUS_DONE, '已完成'),
    (ORDER_STATUS_DELETED, '已删除'),
)